var a="My name is Sneha.";
var i=a.indexOf("is");
console.log(i);
var j=a.split(" ");
console.log(j);
var k=a.endsWith("a");
console.log(k);
var b=" My age is 27.";
var l=a.concat(b);
console.log(l);
var m=a.charAt(4);
console.log(m);
var n=b.replace(" ","|");
console.log(n);
var o=a.slice(11,16);
console.log(o);
var p=a.startsWith("M");
console.log(p);
var q=a.toUpperCase();
console.log(q);
var r=a.toLowerCase();
console.log(r);